// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"n5rncqi7ej","name":"ReactSample","description":"","endpoint":"https://n5rncqi7ej.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:8cb3d066-dacc-4cae-b2cd-2c73bfd94fc5',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'bjjheros-hosting-mobilehub-1305262784',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd25yev35vm2rx6.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_project_id': 'b3b569ee-c05b-48e2-b348-6bd3d9a5e7bc',
    'aws_project_name': 'bjj-heros',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'bjjheros-deployments-mobilehub-1305262784',
    'aws_resource_name_prefix': 'bjjheros-mobilehub-1305262784',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_LJXZjo9UG',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '7ikv12mrvvju594u6im4n1r00p',
}

export default awsmobile;
