// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:5fa5369d-1861-4bb9-b2e8-bc303dac96b3',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'aforceusa-hosting-mobilehub-1762035604',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd11cs00nd745v0.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"aforceusa-mobilehub-1762035604-heros","attributes":[{"name":"userId","type":"S"},{"name":"association","type":"S"},{"name":"created","type":"S"},{"name":"createdBy","type":"S"},{"name":"division","type":"S"},{"name":"firstname","type":"S"},{"name":"joined","type":"S"},{"name":"lastname","type":"S"},{"name":"nickname","type":"S"},{"name":"rank","type":"S"},{"name":"updated","type":"S"},{"name":"updatedBy","type":"S"}],"indexes":[{"indexName":"userId","hashKey":"userId"}],"region":"us-east-1","hashKey":"userId"}],
    'aws_mobile_analytics_app_id': 'f5b6a5456bb9485da5d878f0ef3a607e',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '187808bb-886d-48fb-809a-98e8f0b8ba89',
    'aws_project_name': 'aforce-usa',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'aforceusa-mobilehub-1762035604',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_igKr1wQrS',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '1l6ue6hk5j1g4gaaupntr0htl4',
}

export default awsmobile;
